#!/usr/bin/python

import sys, os

def main(src):
    f = open(src)
    calls = {}
    for line in f:
        fields = line.split(',')
        wav = fields[2]
        start = float(fields[6])
        duration = float(fields[7])
        calls.setdefault(wav, []).append((start, start + duration))

    for wav, pairs in calls.iteritems():
        pairs.sort()
        ls, le = pairs[0]
        combined = []
        for i in range(1, len(pairs)):
            rs, re = pairs[i]
            if rs <= le: #overlap --> merge
                le = re
                print >> sys.stderr, "combining %s-%s and %s-%s" %(ls, le, rs, re)
            else:
                combined.append((ls, le))
                ls = rs
                le = re
        combined.append((ls, le))

        print "%s %s" % (wav, ' '.join("%.2f %.2f" % x for x in combined))


main(sys.argv[1])
